# Generated by Django 3.0.7 on 2022-10-30 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='testimonios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=5000)),
                ('comentario', models.CharField(max_length=5000)),
            ],
        ),
    ]
