# Generated by Django 3.0.7 on 2022-10-30 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TDI', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='cursos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner', models.CharField(max_length=5000)),
                ('banneralt', models.CharField(max_length=5000)),
                ('docente', models.CharField(max_length=5000)),
                ('docentefoto', models.CharField(max_length=5000)),
                ('docentealt', models.CharField(max_length=5000)),
                ('cargo', models.CharField(max_length=5000)),
                ('titulo', models.CharField(max_length=5000)),
                ('categoria', models.CharField(max_length=5000)),
                ('modalidad', models.CharField(max_length=5000)),
                ('duracion', models.CharField(max_length=5000)),
                ('clases', models.CharField(max_length=5000)),
                ('horasClase', models.CharField(max_length=5000)),
                ('horasTotal', models.CharField(max_length=5000)),
                ('horario', models.CharField(max_length=5000)),
                ('dias', models.CharField(max_length=5000)),
                ('calificacion', models.CharField(max_length=5000)),
                ('alumnos', models.CharField(max_length=5000)),
                ('descuento', models.CharField(max_length=5000)),
                ('precioOriginal', models.CharField(max_length=5000)),
                ('precioActual', models.CharField(max_length=5000)),
                ('descripcion', models.CharField(max_length=5000)),
                ('url', models.CharField(max_length=5000)),
                ('urlsilabus', models.CharField(max_length=5000)),
                ('urlsilabustitle', models.CharField(max_length=5000)),
            ],
        ),
    ]
