# Generated by Django 3.0.7 on 2022-10-30 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TDI', '0002_cursos'),
    ]

    operations = [
        migrations.CreateModel(
            name='workshops',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner', models.CharField(max_length=5000)),
                ('titlebanner', models.CharField(max_length=5000)),
                ('titulo', models.CharField(max_length=5000)),
                ('ponente', models.CharField(max_length=5000)),
                ('cargo', models.CharField(max_length=5000)),
                ('horas', models.CharField(max_length=5000)),
                ('calificacion', models.CharField(max_length=5000)),
                ('vistas', models.CharField(max_length=5000)),
                ('enlace', models.CharField(max_length=5000)),
            ],
        ),
    ]
