# Generated by Django 3.0.7 on 2022-10-31 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TDI', '0003_workshops'),
    ]

    operations = [
        migrations.CreateModel(
            name='pagos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=5000)),
                ('nombres', models.CharField(max_length=5000)),
                ('apellidos', models.CharField(max_length=5000)),
                ('correo', models.CharField(max_length=5000)),
                ('celular', models.CharField(max_length=5000)),
                ('curso', models.CharField(max_length=5000)),
                ('medio', models.CharField(max_length=5000)),
                ('voucher', models.CharField(max_length=5000)),
                ('dia', models.CharField(max_length=4)),
                ('mes', models.CharField(max_length=4)),
                ('anio', models.CharField(max_length=4)),
            ],
        ),
    ]
