# Generated by Django 3.0.7 on 2022-10-31 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TDI', '0004_pagos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagos',
            name='voucher',
            field=models.ImageField(blank=True, null=True, upload_to='pagos/'),
        ),
    ]
