# Generated by Django 3.0.7 on 2022-11-02 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TDI', '0004_pagos'),
    ]

    operations = [
        migrations.CreateModel(
            name='comentarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=5000)),
                ('comentario', models.CharField(max_length=50000)),
            ],
        ),
    ]
