# Generated by Django 3.0.7 on 2022-11-02 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TDI', '0006_auto_20221102_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentarios',
            name='anio',
            field=models.CharField(default='año', max_length=4),
        ),
        migrations.AddField(
            model_name='comentarios',
            name='dia',
            field=models.CharField(default='dia', max_length=4),
        ),
        migrations.AddField(
            model_name='comentarios',
            name='mes',
            field=models.CharField(default='mes', max_length=4),
        ),
    ]
