# Generated by Django 3.0.7 on 2022-11-02 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TDI', '0008_auto_20221102_1202'),
    ]

    operations = [
        migrations.CreateModel(
            name='blogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner', models.CharField(max_length=5000)),
                ('banneralt', models.CharField(max_length=5000)),
                ('titulo', models.CharField(max_length=5000)),
                ('descripcion', models.CharField(max_length=5000)),
                ('fechapublicacion', models.CharField(max_length=5000)),
                ('tiempolectura', models.CharField(max_length=5000)),
                ('url', models.CharField(max_length=5000)),
                ('autor', models.CharField(max_length=5000)),
                ('autoralt', models.CharField(max_length=5000)),
                ('fotoautor', models.CharField(max_length=5000)),
            ],
        ),
    ]
