# Generated by Django 3.0.7 on 2022-11-02 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TDI', '0010_auto_20221102_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='dictar_workshop',
            name='anio',
            field=models.CharField(default='año', max_length=4),
        ),
        migrations.AddField(
            model_name='dictar_workshop',
            name='dia',
            field=models.CharField(default='dia', max_length=4),
        ),
        migrations.AddField(
            model_name='dictar_workshop',
            name='mes',
            field=models.CharField(default='mes', max_length=4),
        ),
    ]
